name: 'Chromatic'

on:
  push:
    paths:
      - packages/ui/**

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/ui
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
      - name: Publish to Chromatic
        run: yarn chromatic
        env:
          CHROMATIC_PROJECT_TOKEN:  ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
